language: python
services:
  - docker
sudo: required

python:
- 3.5

env:
- TOXENV=py35-django22
- TOXENV=py38-django22
- TOXENV=quality

before_script:
  - echo -e "[server]\nwait_timeout=28800" | sudo tee -a /etc/mysql/my.cnf
  - mysql -e 'SET @@GLOBAL.wait_timeout=28800'

before_install:
  - docker-compose -f .travis/docker-compose-travis.yml up -d
  - docker exec xqueue bash -c "cd /edx/app/xqueue/xqueue/; pip install -r requirements/travis.txt"
install:
  - docker exec -t xqueue bash -c "
    sudo add-apt-repository ppa:deadsnakes/ppa -y;
    sudo apt-get update -y;
    sudo apt-get install python3.8 python3.8-distutils python3.8-dev -y;"
script:
  - docker exec xqueue bash -c "cd /edx/app/xqueue/xqueue/; TOXENV=${TOXENV} tox"
after_success:
  - pip install -r requirements/travis.txt
  - docker exec xqueue bash -c "cd /edx/app/xqueue/xqueue/; coverage combine; coverage xml"
  - codecov
branches:
  only:
    - master
