language: python
services:
  - docker
sudo: required

branches:
  only:
    - master

before_install:
  - docker-compose -f .travis/docker-compose-travis.yml up -d
  - docker exec xqueue bash -c "cd /edx/app/xqueue/xqueue/; pip3 install -r requirements/travis.txt"

script:
  - docker exec xqueue bash -c "cd /edx/app/xqueue/xqueue/ && tox -e ${TOXENV}"

matrix:
  include:
    - python: 3.5
      env:
        TEST_NAME=test-python
        TOXENV="py35-django22"
      after_success:
        - python3.5 -m pip install -r requirements/travis.txt
        - docker exec xqueue bash -c "cd /edx/app/xqueue/xqueue/; coverage combine; coverage xml"
        - codecov
    - python: 3.8
      env:
        TEST_NAME=test-python
        TOXENV="py38-django22"
      after_success:
        - python3.8 -m pip install -r requirements/travis.txt
        - docker exec xqueue bash -c "cd /edx/app/xqueue/xqueue/; coverage combine; coverage xml"
        - codecov
    - python: 3.5
      env:
        TEST_NAME=quality-python
        TOXENV="quality"
